// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvLjBlsuVgll1zw4iTh96TqQVAQzahHn4',
    appId: '1:512638755537:android:48e19e39a0a7991c08dbf0',
    messagingSenderId: '512638755537',
    projectId: 'e-commerce-9cfa1',
    storageBucket: 'e-commerce-9cfa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUaOkSCzBeXezgMGXaSU8bYF9zseewJ0',
    appId: '1:512638755537:ios:0cbfb1cfe62c5a7d08dbf0',
    messagingSenderId: '512638755537',
    projectId: 'e-commerce-9cfa1',
    storageBucket: 'e-commerce-9cfa1.appspot.com',
    iosClientId: '512638755537-j8cns5imf8er9fi96rb7ib7rhk1hquun.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
